---
# File: tasks/main.yml - Ansible Hubot main tasks

# CentOS tasks
- include: CentOS.yml
  when: ansible_distribution  == "CentOS"

# Ubuntu tasks
- include: Ubuntu.yml
  when: ansible_distribution  == "Ubuntu"
